#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SwipeableCardsExample.Resource", IsApplication=true)]

namespace SwipeableCardsExample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SwipeableCards.Resource.Attribute.SwipeFlingStyle = global::SwipeableCardsExample.Resource.Attribute.SwipeFlingStyle;
			global::SwipeableCards.Resource.Attribute.max_visible = global::SwipeableCardsExample.Resource.Attribute.max_visible;
			global::SwipeableCards.Resource.Attribute.min_adapter_stack = global::SwipeableCardsExample.Resource.Attribute.min_adapter_stack;
			global::SwipeableCards.Resource.Attribute.rotation_degrees = global::SwipeableCardsExample.Resource.Attribute.rotation_degrees;
			global::SwipeableCards.Resource.String.library_name = global::SwipeableCardsExample.Resource.String.library_name;
			global::SwipeableCards.Resource.Style.SwipeFling = global::SwipeableCardsExample.Resource.Style.SwipeFling;
			global::SwipeableCards.Resource.Styleable.SwipeFlingAdapterView = global::SwipeableCardsExample.Resource.Styleable.SwipeFlingAdapterView;
			global::SwipeableCards.Resource.Styleable.SwipeFlingAdapterView_SwipeFlingStyle = global::SwipeableCardsExample.Resource.Styleable.SwipeFlingAdapterView_SwipeFlingStyle;
			global::SwipeableCards.Resource.Styleable.SwipeFlingAdapterView_max_visible = global::SwipeableCardsExample.Resource.Styleable.SwipeFlingAdapterView_max_visible;
			global::SwipeableCards.Resource.Styleable.SwipeFlingAdapterView_min_adapter_stack = global::SwipeableCardsExample.Resource.Styleable.SwipeFlingAdapterView_min_adapter_stack;
			global::SwipeableCards.Resource.Styleable.SwipeFlingAdapterView_rotation_degrees = global::SwipeableCardsExample.Resource.Styleable.SwipeFlingAdapterView_rotation_degrees;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int SwipeFlingStyle = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int max_visible = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int min_adapter_stack = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int rotation_degrees = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int frame = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int helloText = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int item_swipe_bottom_indicator = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int item_swipe_left_indicator = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int item_swipe_right_indicator = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int item_swipe_top_indicator = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int left = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int right = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Buttons = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int SwipeFling = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SwipeFlingAdapterView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int SwipeFlingAdapterView_SwipeFlingStyle = 0;
			
			// aapt resource value: 3
			public const int SwipeFlingAdapterView_max_visible = 3;
			
			// aapt resource value: 2
			public const int SwipeFlingAdapterView_min_adapter_stack = 2;
			
			// aapt resource value: 1
			public const int SwipeFlingAdapterView_rotation_degrees = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
